### ISSUE TITLE
problems with input fields data filling

### ISSUE THREAD

**Issue by kazhamiakin** [SIMPATICOProject/CDV#1]
The mechanism used to implement CDV data values uses <datalist> tag that is not supported on Safari. Moreover, when the input element is inside the form, and the form has autocomplete="off" the data is not populated (also in other browsers).

**Comment by enzosav** [comment]
Bug in IFE toolbar. Solved for Safari data Filling. Data filling for input element inside form tag with attribute autocomplete="off" tested succefully.
