### ISSUE TITLE
Seems CDV Dashboard doesnt like being on a seperate domain as the CDV.

### ISSUE THREAD

**Issue by breningham** [SIMPATICOProject/CDV#10]
As the Issue states,  i have the CDV running on two separate sub-domains. 
CDV Server : http://cdv.sparta.simpatico-project.eu
CDV Dashboard : http://cdv-dash.sparta.simpatico-project.eu

When i try logging into the CDV server using the AAC, i get the authorization screen that is correct but then because i dont have a CDV account, it asks if i want to create an account, which i click create.  and then nothing happens... after some inspecting i get the issues

it tries calling the CDV Server API Endpoints under CDV Dashboard rather than the CDV Server. 
<img width="698" alt="screen shot 2018-07-05 at 13 43 38" src="https://user-images.githubusercontent.com/23170786/42323946-b3eeea2c-8059-11e8-9ed2-0f9aa35397bd.png">
<img width="646" alt="screen shot 2018-07-05 at 13 43 45" src="https://user-images.githubusercontent.com/23170786/42323949-b5ac7820-8059-11e8-9da7-219551a16106.png">

Both Get Method Not allowed or 404. 

here is a copy of my Config: 

```(javascript)

  "system": {
    "host":"http://cdv-dash.sparta.simpatico-project.eu",
    "cdvServer":"http://cdv.sparta.simpatico-project.eu",
    "aacServer":"http://auth.sparta.simpatico-project.eu/aac",
    "account":"/account-manager/api/v1/accounts/",
    "pData":"/pdata-manager/api/v1/pData/",
    "downloadPData":"/pdata-manager/api/v1/pData/download",
    "pDataFields":"/service-manager/api/v1/pdatafields",
        "services":"/service-manager/api/v1/services",
    "clientId":"redacted",
    "authority":"google",
    "cdvDashboardUrl":"/simp_login/login2.html",
    "disable_auth":"false"
  },
  "i18n":{
        "locale": "en"
  }
}
```

**Comment by breningham** [comment]
It also seems that there is a dummy Registration Page that does nothing left in the 'final' product.

**Comment by enzosav** [comment]
As reported, in the other issues, it seems you have not updated the last version where config,json takes into account modules deployed in several servers.

Dummy registration page is provided if used with an idm (like aac) in a registration workflow. If used with google, could be removed.

**Comment by breningham** [comment]
I have in-fact got the latest version as of the 'master' branch pulled from this repo. 
<img width="605" alt="screen shot 2018-07-05 at 14 56 47" src="https://user-images.githubusercontent.com/23170786/42327477-aedfd898-8063-11e8-84c5-a2a328671ece.png">

as a precaution i just force-rebuilt all my docker containers for the CDV, and i still have the same issue.

**Comment by enzosav** [comment]
config.json should be like this ( as you can see in https://github.com/SIMPATICOProject/CDV/blob/master/cdv-dashboard/src/config.json) :

{
  "system": {
    "host":"http://localhost:8080",
    "dashHost":"http://localhost:8080",
    "aacServer":"http://localhost:8080/aac",
    "account":"/account-manager/api/v1/accounts/",
    "pData":"/pdata-manager/api/v1/pData/",
    "downloadPData":"/pdata-manager/api/v1/pData/download",
    "pDataFields":"/service-manager/api/v1/pdatafields",
	"services":"/service-manager/api/v1/services",
    "clientId":"80e7a735-04bf-4737-b6ca-46caac64f823",
    "authority":"google",
   
    "cdvDashboardUrl":"/cdv-dashboard/simp_login/login2.html",
    "disable_auth":"false"
  },
  "i18n":{
  	"locale": "it"
  }
}

Did you have re-compiled?

**Comment by breningham** [comment]
then the issue seems to be that the config file here : https://github.com/SIMPATICOProject/CDV/blob/cdv-dev/docker/Dockerfiles/CDV-dashboard/config/config.json is not following the config file from before. 

Might be easier in the future to make some changes to how you dockerize the CDV. 
i will provide an example in a PR.

**Comment by enzosav** [comment]
The docker deployment is just provided, it fetch automatically the last version of CDV.
See documentation:
https://github.com/SIMPATICOProject/CDV/blob/master/README.md#installation-with-docker

**Comment by enzosav** [comment]
Updated config file in docker  folder
