### ISSUE TITLE
AAC Callback Page is not configurable with docker build

### ISSUE THREAD

**Issue by breningham** [SIMPATICOProject/CDV#12]
AS the Title states, The AAC callback page for the CDV-Dashboard in the Docker version is stuck as Italian, and not possible to change due to the current Structure for the Docker Config.

Following the Config at https://github.com/SIMPATICOProject/CDV/pull/11 would avoid this, maybe we should work together to solve whatever problems there are with that PR.

**Comment by enzosav** [comment]
Call back page is a static one and at moment should be modified for each deployment taking into account layout and pilot branding.
