### ISSUE TITLE
Hi Iberia deployment errors

### ISSUE THREAD

**Issue by smendez-hi** [SIMPATICOProject/CDV#3]
Hi. We found a few errors while deploying all the components in this repo.

In the `account-manager`proyect there is a missing dependency: [commons-logging](https://mvnrepository.com/artifact/commons-logging/commons-logging/1.2). We had to add it in the `pom.xml`
The `pdata-repository` doesn't start. It gives an error when we try `java -jar pdata-repository.jar`.

Also, we deployed all the `.war` files into Tomcat 7 because that is the version we have in the server and everything seems to work. But we know you put Tomcat 8 in the prerequisites. Can we leave it with version 7?

**Comment by enzosav** [comment]
Hi. Tested "mvn package" command (as reported in documentation) for account-manager and it has included commons-logging dependencies.

pdata-repository.jar has not to be launched. It will included in libraries used by pdata-manager module during "mvn package".

Development and test have been performed with Tomcat 8.*
