### ISSUE TITLE
cdv-dashboard deployment npm issues

### ISSUE THREAD

**Issue by smendez-hi** [SIMPATICOProject/CDV#4]
Hi,
We are having problems with the cdv-dashboard module. When running `npm install` we get a few warnings at the end that may be problems. Here is the log https://pastebin.com/npQN2iyX

I think that the versions in `package.json` are not correct but i'm not sure. Because for example `@angular/animations @4.3.6` needs `@angular/core@4.3.6` but the version trying to install is `4.0.1`.

**Comment by enzosav** [comment]
Updated package.json dependences. Tested successfully

**Comment by smendez-hi** [comment]
The installation runs correctly although we got some warnings at the end. We get some error from `webpack` when running `npm install` but we see the page on the browser so... We are uploading it to our server to test it better with all the components.

**Comment by smendez-hi** [comment]
Could you tell me your npm version? `npm -v`. We still have problems.

**Comment by jrgaston-hib** [comment]
Is neccesary to install angular globally?

I have installed angular inside the project (see attached picture) but when I try to do npm install failed.

![captura de pantalla de 2017-09-20 09 50 56](https://user-images.githubusercontent.com/16797922/30632763-8ff4e84a-9de9-11e7-97d7-f2fdc3caffa4.png)

**Comment by enzosav** [comment]
Component tested with environment:
node (node -v): 6.10.0
npm (npm -v):3.10.10.

If you are problem in your prod environment you can deploy (copy) on server the dist folder you have previously generated. Once copied the folder you have to modify config.json file with the actual configuration properties.  (see https://github.com/SIMPATICOProject/CDV/blob/master/cdv-dashboard/doc/deployment.md#configuration)

**Comment by smendez-hi** [comment]
Please don't close issues that are not resolved. The folder `dist` doesn't get generated because of the errors with angular.

**Comment by enzosav** [comment]
From picture posted npm is not installed or cannot be executed from the path you are.  

You have to solve node and npm installation
