### ISSUE TITLE
CDV integration with IFE

### ISSUE THREAD

**Issue by jrgaston-hib** [SIMPATICOProject/CDV#5]
There are an errors in CDV when trying to integrate with IFE.
For example:
POST https://simpatico.hi-iberia.es:4570/pdata-manager/api/v1/getPData 400 (Bad Request) OR
errorCallback is not a function OR
POST https://simpatico.hi-iberia.es:4570/pdata-manager/api/v1/postPData?mode=append 400 (Bad Request) 

I downloaded code from cdv_integration branch from IFE project but I had the same errors. 
With these code (cpd_integration) If button "manage your data" is clicked, new tab opens with the same content. Nothing happens.

I attach the errors of the branch code hi_iberia

[console-errors_hi-iberia-branch.txt](https://github.com/SIMPATICOProject/CDV/files/1337550/console-errors_hi-iberia-branch.txt)

**Comment by enzosav** [comment]
Are https://simpatico.hi-iberia.es:4570/pdata-manager services reachable?
It seems that https://simpatico.hi-iberia.es:4570 is not reachable.
Is service page proper configured?

Please provide further info about the page you installed IFE.

Furthermore, do you have saved service description? Let's try with

https://simpatico.hi-iberia.es:4570/service-manager/api/v1/services (not reachable externally)

to verify if your service (with the same "simpaticoEservice" variable inserted in service page ) as described in https://github.com/SIMPATICOProject/IFE/tree/cdv_integration#12-global-variables

**Comment by enzosav** [comment]
>With these code (cpd_integration) If button "manage your data" is clicked, new tab opens with the same content. Nothing happens.

see:
https://github.com/SIMPATICOProject/IFE/tree/cdv_integration#26-configure-citizen-data-vault-module

you have to modify "cdvDashUrl:'http://localhost:8080/cdv-dashboard/index.html" variable according to your cdv-dashboard installation (see https://github.com/SIMPATICOProject/CDV/blob/master/cdv-dashboard/doc/deployment.md#detailed-documentation)

**Comment by jrgaston-hib** [comment]
Yes, https://simpatico.hi-iberia.es:4570/pdata-manager and https://simpatico.hi-iberia.es:4570 are reachable. Is it possible you have a firewall blocking the connetion?

https://simpatico.hi-iberia.es:4570/pdata-manager shows a hello world page.
https://simpatico.hi-iberia.es:4570 shows a default page to acces to APIs, dashboard or IFE (it's our homepage).
https://simpatico.hi-iberia.es:4570/service-manager/api/v1/services shows all blank.

I copied our ife configuration (simpatico-ife.js): 
 cdvUI.getInstance().init({
    endpoint: 'https://simpatico.hi-iberia.es:4570',
    serviceID: simpaticoEservice,
    serviceURL: 'https://simpatico.hi-iberia.es:4570/IFE/'+simpaticoEservice+'_es.html',
    dataFields: simpaticoMapping,
    cdvColor: '#008000',
    dialogTitle: 'Citizen Data Vault',
    tabPFieldsTitle: 'Mis Datos',
    entryMessage: 'Bienvenido a SIMPATICO',
    statusMessage: 'Ahora puedes seleccionar/actualizar tus datos personales para rellenar campos.',
    notextMessage: 'Ningún campo seleccionado',
    dialogSaveTitle: 'Datos Salvados',
    dialogSaveMessage: 'Datos salvados correctamente.',
    statusMessageNoAccount: "No hay cuenta de Simpatico ascociada. ¿Crear?",
    statusMessageNoActive: "Simpatico no está activo para este servicio. ¿Activar?",
    tabSettingsTitle: 'Configuración'
  });


The global variable in the service are: 
<script type="text/javascript">
	  var simpaticoEservice = "BS607A_form"; // Eservice example
	  var simpaticoMapping=["BS607A.Entidad.txtNombre","BS607A.Entidad.txtApel2","BS607A.Entidad.txtApel1","BS607A.Entidad.txtNifCif","BS607A.Entidad.txtDireccion","BS607A.Entidad.txtParroquia","BS607A.Entidad.txtLugar","BS607A.Entidad.txtCodigoPostal","BS607A.Entidad.txtLocalidad","BS607A.Entidad.txtPais","BS607A.Entidad.txtTelefono","BS607A.Entidad.txtMovil","BS607A.Entidad.txtEmail","BS607A.Declarante.txtNombre","BS607A.Declarante.txtApel2","BS607A.Declarante.txtApel1","BS607A.Declarante.txtNifCif"];
	  var ERROR_LABELS = {
      	'block1' : 'Phone number is required'
      }
</script>


I think all is correct

**Comment by enzosav** [comment]
If https://simpatico.hi-iberia.es:4570/service-manager/api/v1/services shows all blank then you never uploaded service description for service  (simpaticoEservice =BS607A_form).

See https://github.com/SIMPATICOProject/CDV/blob/master/service-manager/doc/deployment.md#detailed-documentation

and https://github.com/SIMPATICOProject/CDV/tree/master/service-manager/doc/service-descriptions
to update service descriptions

Service descriptions have just been deployed during Sheffield GA meeting.

**Comment by jrgaston-hib** [comment]
Sorry, https://simpatico.hi-iberia.es:4570/service-manager/api/v1/services shows an empty array. 
But I think the problem is the same, right?

**Comment by samuelmgalan** [comment]
Hi,
The dump for MongoDB is still the same and doesn't have the BS613B service definition. Just in case I deleted the personalDataMB collection and created all again with `mongorestore` but is still the same. 
And https://simpatico.hi-iberia.es:4570/service-manager/api/v1/services still returns an empty array.

**Comment by enzosav** [comment]
Checked dump file : https://github.com/SIMPATICOProject/CDV/blob/master/service-manager/dump/personalDataMB/serviceRegistry.bson and it contains service descriptions.
Anyway you can store service descriptions  that you can find in https://github.com/SIMPATICOProject/CDV/tree/master/service-manager/doc/service-descriptions

by means of POST request (https://simpatico.hi-iberia.es:4570/service-manager/api/v1/services) as described in:

https://github.com/SIMPATICOProject/CDV/blob/master/service-manager/doc/deployment.md#database-creation

**Comment by jrgaston-hib** [comment]
First, we use post method to put services in own server. But we had to remove "serviceUri" : "http://localhost:8080/IFE/BS613B.html", in each service to get a 200 response. Otherwise we get 400 or 415 error.

So, now if we do a get request to https://simpatico.hi-iberia.es:4570/service-manager/api/v1/services we get the services (2 elements in an array) but it doesnt work correctly in IFE.
In IFE we had these errors:

![ife](https://user-images.githubusercontent.com/16797922/31123950-3d943672-a83a-11e7-8ae7-6a93877a7461.png)


We deployed also another IFE version, with code from cdv_integration and in this new version we get the same errors:

![ife_cdv_integration](https://user-images.githubusercontent.com/16797922/31123949-3af93db8-a83a-11e7-8e24-9e9ec0a6bf18.png)

**Comment by jrgaston-hib** [comment]
I clarify that now we have a "hack" in IFE (not IFE_CDV_INTEGRATION) code to insert data to the form because the cdv does not work correctly.

**Comment by enzosav** [comment]
From the screenshot we see a bad request on  https://simpatico.hi-iberia.es:4570/pdata-manager/api/v1/getPData request. 
From screenshot we cannot see the payload of request, but it seems that CDV APIs are not updated with the last versions (v1.0)

**Comment by enzosav** [comment]
UPDATE. By re-reading your previous comment : "First, we use post method to put services in own server. But we had to remove "serviceUri" : "http://localhost:8080/IFE/BS613B.html", in each service to get a 200 response. Otherwise we get 400 or 415 error." We can confirm you have v0.9 version of CDV installed not the last.

**Comment by jrgaston-hib** [comment]
CDV and IFE is up to date. Also we have another branch of IFE (IFE_CDV_INTEGRATION) but doesnt work neither.
To view payload request try to create an account in own Simpatico service and view the requests in console. 
Link to create an account: https://simpatico.hi-iberia.es:4570/aac/internal/register

**Comment by smendez-hi** [comment]
Where is version 1.0? Is master branch? That's the one we are using.

**Comment by enzosav** [comment]
I've just registered in https://simpatico.hi-iberia.es:4570/IFE/BS607A/BS607A.html and I see the payload  
{"user_id":"54","slr_id":"59d4957c59cf280b613ee9a6","properties":[]} 

but it should be like this:
{"user_id":"54","slr_id":"59d4957c59cf280b613ee9a6","slr_token":"eyJhbGciOiJIUzI1NiJ9.eyJzZXJ2aWNlSWQiOiJCUzYwN0EiLCJzZXJ2aWNlVXJpIjoiaHR0cDovL2xvY2FsaG9zdDo4MDgwL0lGRS9CUzYwN0EuaHRtbCIsInNlcnZpY2VOYW1lIjoiUFJPR1JBTUEgQklFTkVTVEFSIEVOIEJBTE5FQVJJT1MiLCJzdXJyb2dhdGVJZCI6IjEiLCJhY2NvdW50SWQiOiJWaW5jZW56by5TYXZhcmlubzEzIiwidXNlcm5hbWUiOiJWaW5jZW56by5TYXZhcmlubzEzIiwiY3JlYXRlZCI6eyJvZmZzZXQiOnsidG90YWxTZWNvbmRzIjowLCJpZCI6IloiLCJydWxlcyI6eyJ0cmFuc2l0aW9uUnVsZXMiOltdLCJ0cmFuc2l0aW9ucyI6W10sImZpeGVkT2Zmc2V0Ijp0cnVlfX0sInpvbmUiOnsiaWQiOiJVVEMiLCJydWxlcyI6eyJ0cmFuc2l0aW9uUnVsZXMiOltdLCJ0cmFuc2l0aW9ucyI6W10sImZpeGVkT2Zmc2V0Ijp0cnVlfX0sImRheU9mTW9udGgiOjQsImhvdXIiOjgsIm1pbnV0ZSI6MTMsIm1vbnRoIjoiT0NUT0JFUiIsIm1vbnRoVmFsdWUiOjEwLCJuYW5vIjo2OTQwMDAwMDAsInNlY29uZCI6NTQsInllYXIiOjIwMTcsImRheU9mV2VlayI6IldFRE5FU0RBWSIsImRheU9mWWVhciI6Mjc3LCJjaHJvbm9sb2d5Ijp7ImlkIjoiSVNPIiwiY2FsZW5kYXJUeXBlIjoiaXNvODYwMSJ9fSwic2VydmljZUxpbmtTdGF0dXNSZWNvcmRzIjpbXX0.lGdHw-t-EW2Ujog9Q8ejK8Q-W90z9JS1kRgWsSi_qh4","properties":[]}

**Comment by smendez-hi** [comment]
What is `slr_token`? The `aac_token` variable? 
Also... how do we know if we have version 1.0?

**Comment by enzosav** [comment]
Issue solved, updated wars in application containers
