### ISSUE TITLE
docker problem

### ISSUE THREAD

**Issue by mirkoperillo** [SIMPATICOProject/CDV#8]
I tried to run your docker configuration but executing `./run.sh` I have this error

```
Using production Config
run.sh: 4: run.sh: Syntax error: "(" unexpected
```

**Comment by enzosav** [comment]
Please, provide in which environment you executed the script. Just tested in Ubuntu 16 and it works.

**Comment by mirkoperillo** [comment]
Ubuntu 14.04

I tried it using either bash and sh

**Comment by enzosav** [comment]
reproduced error in Ubuntu 14.04 with
#sudo sh run.sh
no error with:
# sudo bash run.sh

**Comment by mirkoperillo** [comment]
this resolves my issue
